### ISSUE TITLE
Bug on mobile device number input

### ISSUE THREAD

**Issue by TafadzwaD** [tonghoai/vue-otp-2#2]
When I use the OTP component on a mobile device I am experiencing a bug where numbers are not being identified.  Works fine on Desktop. I have also tried it out using the demo link you provided on your repo and it's the same issue.. 

https://user-images.githubusercontent.com/28431370/137512733-2679a9d8-f05c-4bc0-adce-fd49fcfef444.mp4

**Comment by tonghoai** [comment]
Hi TafadzwaD, can you send me the device info?

**Comment by TafadzwaD** [comment]
Samsung S8+.. Same happens on a Samsung A21 .. Thank you

**Comment by tonghoai** [comment]
I found the problem, it seems keypress event on Samsung phone's keyboard is not working as expected. I'm working on a fix!

**Comment by TafadzwaD** [comment]
@tonghoai  It is now working as expected.. Thank you.. I have to click next on every number input so that I can input the remaining numbers on the blocks... Kindly consider triggering next after a input has been supplied on the bloc(as an enhancement in the future).. 

Is it ok if I close this issue?

**Comment by tonghoai** [comment]
I have tested everything and it works fine on Samsung and other. I can enter consecutively without clicking next input. Have you tried clearing the cache? Or you can send me a video of the problem!

**Comment by tonghoai** [comment]
Hi TafadzwaD, thank you for your feedback. I have released version 1.0.4 to fix!

**Comment by TafadzwaD** [comment]
Thank you for the fix!!! Now working perfectly. Thanks for this wonderful
module!!😃⚡️⚡️

**Comment by tonghoai** [comment]
👏👏👏. GG @TafadzwaD

**Comment by TafadzwaD** [comment]
I have closed this issue. Thank you for solving it😃
