### ISSUE TITLE
Resize input box width

### ISSUE THREAD

**Issue by brambrc** [tonghoai/vue-otp-2#3]
Hi, first i love using vue-otp-2 and its really help me with my work !. But i have difficulties when trying to resize the input box. it seems, directly messing with style doesn't worked, i tried to achieve the input box size in the bottom picture. Can you please tell me how and where to change the input width?
![Screen Shot 2021-10-26 at 15 46 04](https://user-images.githubusercontent.com/33341721/138843486-e0f71374-025c-44d6-b04c-a917fd459e8c.png)
![Screen Shot 2021-10-26 at 15 48 55](https://user-images.githubusercontent.com/33341721/138844006-765554ba-a235-48bd-9d94-ec3fdee9124e.png)

**Comment by tonghoai** [comment]
Hi @brambrc, you can customize it using **global** css. Try it:
```scss
.vue-otp-2 {
  input {
    height: 30px;
    width: 30px;
  }
}
```

**Comment by brambrc** [comment]
> Hi @brambrc, you can customize it using **global** css. Try it:
> 
> ```css-scss
> .vue-otp-2 {
>   input {
>     height: 30px;
>     width: 30px;
>   }
> }
> ```

![Screen Shot 2021-10-26 at 16 34 51](https://user-images.githubusercontent.com/33341721/138851890-de6f165c-571f-4ff0-b17d-42b14a91f11e.png)


![Screen Shot 2021-10-26 at 16 31 04](https://user-images.githubusercontent.com/33341721/138851313-4ffa5145-15e7-46da-86eb-2f86de43dda2.png)


hi already try it, but seems still not working, when adding the style using global css, its adding new element on inspect element instead replacing the old one.

But when i try to edit the css with inspect element, and changing the max-width seems very effective, but i can't find the max-width element on the css.

**Comment by tonghoai** [comment]
@brambrc It looks like there is a css conflict about the input tag somewhere. If possible, try adding the `!important` attribute:
```scss
.vue-otp-2 {
  input {
    max-width: 30px !important;
  }
}
```

**Comment by brambrc** [comment]
> @brambrc It looks like there is a css conflict about the input tag somewhere. If possible, try adding the `!important` attribute:
> 
> ```css-scss
> .vue-otp-2 {
>   input {
>     max-width: 30px !important;
>   }
> }
> ```

never cross my mind, that i need to do is just add !important, now it's worked !! thankss

**Comment by tonghoai** [comment]
👏👏👏 GG @brambrc 🥳
